### ISSUE TITLE
Not woring on node 4.2 :(

### ISSUE THREAD

**Issue by garronej** [wessberg/Marshaller#1]
![image](https://user-images.githubusercontent.com/6702424/31310052-515eec60-ab91-11e7-8d0e-1d7c14c6ab79.png)

**Comment by wessberg** [comment]
Hi @garronej. That's right :-)

`Marshaller` supports node: >= 7.4.0.

Generally I ship libraries targeting the latest Node version so that the consumers of the plugin can decide which ES-version to support by further transpiling if required.

I'm gonna close the issue, but please feel free to open a new issue if you have further issues or comments. And thanks for your input!

**Comment by garronej** [comment]
Hi @wessberg i am interested.

So if I understand you well, instead of targeting the lower ES version your library can transpile to you always target es2017.

Is there a perticulare reason for you to do so?
Is it that transpiling down to es3 induce a loss of performance?
Is it for reducing the size of the js files?

Because let's say I want to use one of your libs on raspberry or on the browser how do I do to transpile your lib ? It sound like a lot of work...

Regards

**Comment by wessberg** [comment]
Hi again, @garronej.

Thanks for your comment,

By supporting the newest ES version, clients can include the library and let the build-step, for example with [babel-preset-env](https://github.com/babel/babel-preset-env), transpile according to a [browserslist](https://github.com/ai/browserslist) configuration.

Performance-wise, some of the benefits are:

- The source code will be smaller and potentially more efficient, depending on the engine and features used.
- When using generators or async functions, shipping ES3/ES5 compatible code requires helper functions such as the [regenerator runtime](https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime) or, as is the example with Typescript, inlined helper functions (with or without tslib).
- Even though it is not directly relevant to this library, transpiling ES2015 classes to ES3/ES5 may require overwriting the prototype of built-ins to support new features such as the Custom Elements v1 API.

Also, Marshaller, like my other libraries, is built to be able to function within a dependency injection system which is a requirement for my own projects as well as the company I work for. Here it is absolutely essential that I ship ES2015 classes with support for initializer values.

In regard to your last point - the thing about how to use it on a Raspberry or in the browser, I'd say both are great arguments for not shipping ES3/ES5 compatible code as a library via NPM, but rather let the end-user such as yourself decide how to ship it since:

Many companies ship multiple bundles, targeting older and newer browsers. We're always interested in shipping the smallest possible code to the client, and newer language syntax allows us to express the same concepts with fewer lines of code - which is awesome :-)

If you decide to use node modules in a browser environment, I'm gonna assume you use something like Webpack or Rollup. Here, you can transpile your source code, including the libraries you depend on, with Typescript or babel (or even both). That gives *you*, not *me*, control over how your code will look in the end. And it makes *you* the decider of precisely which browser or node version *you* want to support.

And, newer Node versions and even all modern browsers support most of the ES2015+ features. In the NPM ecosystem, it has become the norm to assume none of these features are available, but I'm giving the consumers of this library the freedom to decide for themselves which environment to target.

Hope it makes sense.
And you're quite welcome to get back to me if you have any comments.
Best regards

**Comment by garronej** [comment]
Thank you for your detailed response this is food for thought, I learned some stufs.

Have a great day
